# Generated by Django 3.1.1 on 2021-07-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('head0', models.CharField(max_length=100)),
                ('chead0', models.CharField(max_length=2000)),
                ('head1', models.CharField(max_length=100)),
                ('chead1', models.CharField(max_length=2000)),
                ('head2', models.CharField(max_length=100)),
                ('chead2', models.CharField(max_length=2000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
