# Generated by Django 3.1.1 on 2021-07-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='genre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
