# Generated by Django 3.1.1 on 2021-06-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210630_2339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
